## Imports

# Base
source = hyprland/base.conf
source = hyprland/environment.conf
source = hyprland/execs.conf
source = hyprland/keybinds.conf
source = hyprland/plugins.conf
source = hyprland/rules.conf
source = hyprland/style.conf

# User
source = user/base.conf
source = user/environment.conf
source = user/execs.conf
source = user/keybinds.conf
source = user/plugins.conf
source = user/rules.conf
source = user/style.conf