#!/bin/bash

CONFIG_FILES="$HOME/.config/waybar/niri/config.jsonc $HOME/.config/waybar/niri/materialyou.css $HOME/.config/waybar/niri/modules.jsonc"

trap "killall waybar" EXIT

while true; do
    waybar -c "$HOME/.config/waybar/niri/config.jsonc" -s "$HOME/.config/waybar/niri/materialyou.css" &
    inotifywait -e create,modify $CONFIG_FILES
    killall waybar
done
