#!/bin/bash

CONFIG_FILES="$HOME/.config/waybar/hyprland/config.jsonc $HOME/.config/waybar/hyprland/style.css  $HOME/.config/waybar/hyprland/modules.jsonc"

trap "killall waybar" EXIT

while true; do
    waybar -c "$HOME/.config/waybar/hyprland/config.jsonc" -s "$HOME/.config/waybar/hyprland/style.css" &
    inotifywait -e create,modify $CONFIG_FILES
    killall waybar
done
