# Auto-Execs

# Apps
exec-once = zen-browser
windowrulev2 = workspace 1 silent, class:zen
exec-once = discord
windowrulev2 = workspace 2 silent, class:discord
exec-once = audiorelay
windowrulev2 = workspace 10 silent, class:com-azefsw-audioconnect-desktop-app-MainKt
