## Plugins
plugin {
    borders-plus-plus {
        add_borders = 1

        col.border_1 = rgb(000000)

        natural_rounding = no
    }

    dynamic-cursors {
        enabled = true

        mode = stretch

        stretch {
            limit = 7000
            function = negative_quadratic
        }

        shake {
            enabled = false
        }
    }

    hyprfocus {
        enabled = false

        focus_animation = flash

        flash {
            flash_opacity = 0.8
            out_speed = 1
        }
    }

    hyprexpo {
        rows = 3
        gap_size = 0
        bg_col = rgba(00000055)
        workspace_method = first 1
    }

    scroller {
        column_widths = onethird onehalf twothirds one
    }
}
