## Rules

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# Tkinter
windowrule = float,class:Tk

# waybar blur
layerrule = blur, waybar
layerrule = ignorezero, waybar

# swaync blur
layerrule = blur, swaync-control-center
layerrule = ignorezero, swaync-control-center
layerrule = blur, swaync-notification-window
layerrule = ignorezero, swaync-notification-window

# wlogout blur
layerrule = blur, logout_dialog

# screenshot fix
layerrule = noanim, hyprpicker
layerrule = noanim, selection