shell /usr/bin/fish
font_family Iosevka
window_padding_width 10
tab_bar_style slant
tab_bar_align center
tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{tab.last_focused_progress_percent}{title}"

include colors.conf
